In [1]:
1 + 1

2

In [4]:
import numpy as np
lst=[1,2,3,4]
arr=np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
arr1=np.array([[1,2,3],[4,5,6]])

In [8]:
arr1.shape

(2, 3)

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [14]:
arr1.dtype

dtype('int32')

In [15]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [21]:
A = np.arange(1,20,2)

In [25]:
B = A.reshape(2,5)

In [26]:
B.shape

(2, 5)

In [29]:
C = np.array(range(1,20,3))
C

array([ 1,  4,  7, 10, 13, 16, 19])

In [30]:
#Quickly create an array element in the reverse order 
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [31]:
#Quickly create an array between 1 to 20 and  I want element 40 which are equaly spaced and reshape into (20,2)

A = np.linspace(1,20,40)
A.reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [32]:
# Create zeros in two dimensial
A = np.zeros((3,4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
# Create onces in two dimensial & three diamential 

B = np.ones((2,5))
print(B)
print("-------------------------------")
C = np.ones((5,2,8))
print(C)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-------------------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [36]:
5 + B 

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [37]:
#Create 4 x 4 identity matric 
D = np.eye(4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
E = np.identity(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Create an array random number with uniform distribution (uniform ranges 0 to 1 )

A = np.random.rand(2,3)
A

array([[0.30235294, 0.87410107, 0.54307966],
       [0.9664954 , 0.11431843, 0.99287356]])

In [43]:
# Create an array number 1 to 100 with 50  having randomly selected & make 4,4 array.
A = np.random.randint(1,100,50)
B = np.random.randint(1,100,(4,4))
print(A)
print("-----------------------------------------")
print(B)

[41 53 85 99 66 96 77 47 80 21 81 52 92  7 94  5 27 31 86 62 78 50 31 92
 82 68 59  3 28 10 54 20 94 26  6  8 57 74 41 90 20 66 38 21 45 21 18 24
 11  4]
-----------------------------------------
[[89 33  6 91]
 [63  6 28 98]
 [51 42  4 34]
 [23 44 23  4]]


In [44]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [46]:
arr[-1]

10

In [47]:
arr[-1:7:-1]

array([10,  9,  8])

In [48]:
arr[2:7:3]

array([2, 5])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [53]:
arr1 = np.random.randint(2,100,20).reshape(5,4)
arr1

array([[40, 37, 10, 43],
       [72, 19,  7, 17],
       [66, 43, 98, 94],
       [66, 91, 76,  3],
       [45, 30,  9, 45]])

In [54]:
arr1[0:3]

array([[40, 37, 10, 43],
       [72, 19,  7, 17],
       [66, 43, 98, 94]])

In [55]:
arr1[0:3,0:3]

array([[40, 37, 10],
       [72, 19,  7],
       [66, 43, 98]])

In [60]:
arr1[3:,1:]

array([[91, 76,  3],
       [30,  9, 45]])

In [63]:
arr1[2:4,1:3]

array([[43, 98],
       [91, 76]])

In [62]:
arr1

array([[40, 37, 10, 43],
       [72, 19,  7, 17],
       [66, 43, 98, 94],
       [66, 91, 76,  3],
       [45, 30,  9, 45]])

In [80]:
np.sqrt(arr1)

array([[6.32455532, 6.08276253, 3.16227766, 6.55743852],
       [8.48528137, 4.35889894, 2.64575131, 4.12310563],
       [8.1240384 , 6.55743852, 9.89949494, 9.69535971],
       [8.1240384 , 9.53939201, 8.71779789, 1.73205081],
       [6.70820393, 5.47722558, 3.        , 6.70820393]])

In [81]:
np.exp(arr1)

array([[2.35385267e+17, 1.17191424e+16, 2.20264658e+04, 4.72783947e+18],
       [1.85867175e+31, 1.78482301e+08, 1.09663316e+03, 2.41549528e+07],
       [4.60718663e+28, 4.72783947e+18, 3.63797095e+42, 6.66317622e+40],
       [4.60718663e+28, 3.31740010e+39, 1.01480039e+33, 2.00855369e+01],
       [3.49342711e+19, 1.06864746e+13, 8.10308393e+03, 3.49342711e+19]])

In [82]:
np.log10(arr1)

array([[1.60205999, 1.56820172, 1.        , 1.63346846],
       [1.8573325 , 1.2787536 , 0.84509804, 1.23044892],
       [1.81954394, 1.63346846, 1.99122608, 1.97312785],
       [1.81954394, 1.95904139, 1.88081359, 0.47712125],
       [1.65321251, 1.47712125, 0.95424251, 1.65321251]])

In [85]:
arr1[2:]=1000
arr1

array([[  40,   37,   10,   43],
       [  72,   19,    7,   17],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [86]:
# Brodcasting opration
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr1[2:]=100

In [88]:
arr1

array([  1,   2, 100, 100, 100, 100, 100, 100, 100])