In [1]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
# Create a DataFrame 
df = pd.DataFrame(data=np.arange(0, 20).reshape(5, 4),
                  index=['row1', 'row2', 'row3', 'row4', 'row5'],
                  columns=["Column1", "Column2", "Column3", "Column4"])

In [8]:
df

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [10]:
df.head()

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [11]:
df.tail()

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [12]:
df.head(3)

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11

In [13]:
df.tail(3)

Column1  Column2  Column3  Column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [14]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [15]:
df[['Column1']]

Column1
row1        0
row2        4
row3        8
row4       12
row5       16

In [17]:
type(df[['Column1']])

pandas.core.frame.DataFrame

In [16]:
df['Column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: Column1, dtype: int32

In [18]:
type(df['Column1'])

pandas.core.series.Series

In [19]:
df.loc[['row1','row3']]

Column1  Column2  Column3  Column4
row1        0        1        2        3
row3        8        9       10       11

In [20]:
type(df.loc[['row1','row3']])

pandas.core.frame.DataFrame

In [21]:
df.iloc[0:3,:]

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11

In [22]:
df.iloc[0:3,0:2]

Column1  Column2
row1        0        1
row2        4        5
row3        8        9

In [25]:
df.iloc[2:4,1:3]

Column2  Column3
row3        9       10
row4       13       14

In [26]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [34]:
df = pd.DataFrame(data=[[1, np.nan, 2], [1, 3, 4],[4,4,3]],
                  index=['row1', 'row2','row3'],
                  columns=['Column1', 'Column2', 'Column3'])

df

Column1  Column2  Column3
row1        1      NaN        2
row2        1      3.0        4
row3        4      4.0        3

In [35]:
df.isnull()

Column1  Column2  Column3
row1    False     True    False
row2    False    False    False
row3    False    False    False

In [36]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [37]:
df.isna()

Column1  Column2  Column3
row1    False     True    False
row2    False    False    False
row3    False    False    False

In [38]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [41]:
df['Column1'].value_counts()

Column1
1    2
4    1
Name: count, dtype: int64

In [42]:
df['Column1'].unique()

array([1, 4], dtype=int64)

In [43]:
df['Column1'].nunique()

2

In [44]:
df

Column1  Column2  Column3
row1        1      NaN        2
row2        1      3.0        4
row3        4      4.0        3

In [45]:
df = pd.DataFrame({'A':[1,2,3], 'B':[1,1,1]})
df

A  B
0  1  1
1  2  1
2  3  1

In [46]:
df['A'].unique()

array([1, 2, 3], dtype=int64)

In [49]:
df['B'].unique()

array([1], dtype=int64)

In [50]:
df['A'].nunique()

3

In [51]:
df['B'].nunique()

1

In [52]:
df.nunique()

A    3
B    1
dtype: int64

In [55]:
df.nunique(axis=0) # all the row index (verticle)

A    3
B    1
dtype: int64

In [56]:
df.nunique(axis=1) # all the Column index (Horizontal)

0    1
1    2
2    2
dtype: int64

In [58]:
# Create a DataFrame 
df = pd.DataFrame(data=np.arange(0, 20).reshape(5, 4),
                  index=['row1', 'row2', 'row3', 'row4', 'row5'],
                  columns=["Column1", "Column2", "Column3", "Column4"])

In [59]:
df['Column1']>5

row1    False
row2    False
row3     True
row4     True
row5     True
Name: Column1, dtype: bool

In [60]:
df[df['Column1']>5]

Column1  Column2  Column3  Column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [73]:
df.to_csv('test.csv',index=False)

In [74]:
df1=pd.read_csv('test.csv')
df1

Unnamed: 0  Column1  Column2  Column3  Column4
0       row1        0        1        2        3
1       row2        4        5        6        7
2       row3        8        9       10       11
3       row4       12       13       14       15
4       row5       16       17       18       19

In [76]:
df.drop(columns=['Unnamed: 0'], inplace=True)


In [77]:
df

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [81]:
!pip install openpyxl



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [82]:
df.to_excel('test.xlsx')

In [90]:
df=pd.read_excel('test.xlsx')
df

Unnamed: 0  Column1  Column2  Column3  Column4
0           0        0        1        2        3
1           1        4        5        6        7
2           2        8        9       10       11
3           3       12       13       14       15
4           4       16       17       18       19

In [91]:
df.drop(columns=['Unnamed: 0'], inplace=True)
df

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [93]:
data = {
    "employee": "Bhimrao",
    "email": "bhimrao.pawar@gmail.com",
    "job_profile": ["Team Lead", "Devil"]
}


In [94]:
type(data)

dict

In [99]:


data = {
    "employee": "Bhimrao",
    "email": "bhimrao.pawar@gmail.com",
    "job_profile": ["Team Lead", "Devil"]
}

df2= pd.DataFrame.from_dict(data, orient='index').T


In [100]:
df2

employee                    email         job_profile
0  Bhimrao  bhimrao.pawar@gmail.com  [Team Lead, Devil]

In [101]:
df2['salary']=100

In [102]:
df2

employee                    email         job_profile  salary
0  Bhimrao  bhimrao.pawar@gmail.com  [Team Lead, Devil]     100

In [104]:
df2['job_profile']

0    [Team Lead, Devil]
Name: job_profile, dtype: object

In [110]:

import json

data = [{
    "employee": "Bhimrao",
    "email": "bhimrao.pawar@gmail.com",
    "job_profile": ["Team Lead", "Devil"]
}]

json_string = json.dumps(data)


C:\Users\bhimr\AppData\Local\Temp\ipykernel_3876\717344000.py:11: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_json(json_string, orient='records')


In [112]:

df2 = pd.read_json(json_string, orient='records')
df2

C:\Users\bhimr\AppData\Local\Temp\ipykernel_3876\927022387.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_json(json_string, orient='records')


employee                    email         job_profile
0  Bhimrao  bhimrao.pawar@gmail.com  [Team Lead, Devil]

In [118]:
import pandas as pd
import json

data = {
    "row1": {"employee": "Bhimrao", "email": "bhimrao.pawar@gmail.com", "job_profile": ["Team Lead", "Devil"]}
}

json_string = json.dumps(data)



C:\Users\bhimr\AppData\Local\Temp\ipykernel_3876\1788062680.py:10: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_json(json_string, orient='index')


In [120]:

df2 = pd.read_json(json_string, orient='index')
df2

C:\Users\bhimr\AppData\Local\Temp\ipykernel_3876\1980813668.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_json(json_string, orient='index')


employee                    email         job_profile
row1  Bhimrao  bhimrao.pawar@gmail.com  [Team Lead, Devil]

In [122]:
import pandas as pd
df = pd.DataFrame([['a','b'],['c','d']],
                  index=['row1','row2'],
                  columns=['col1','col2'])

In [123]:
df

col1 col2
row1    a    b
row2    c    d

In [125]:
df = pd.DataFrame(data=np.arange(0, 20).reshape(5, 4),
                  index=['row1', 'row2', 'row3', 'row4', 'row5'],
                  columns=["Column1", "Column2", "Column3", "Column4"])
df

Column1  Column2  Column3  Column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [126]:
df.to_json()

'{"Column1":{"row1":0,"row2":4,"row3":8,"row4":12,"row5":16},"Column2":{"row1":1,"row2":5,"row3":9,"row4":13,"row5":17},"Column3":{"row1":2,"row2":6,"row3":10,"row4":14,"row5":18},"Column4":{"row1":3,"row2":7,"row3":11,"row4":15,"row5":19}}'

In [127]:
df.to_json(orient='records')

'[{"Column1":0,"Column2":1,"Column3":2,"Column4":3},{"Column1":4,"Column2":5,"Column3":6,"Column4":7},{"Column1":8,"Column2":9,"Column3":10,"Column4":11},{"Column1":12,"Column2":13,"Column3":14,"Column4":15},{"Column1":16,"Column2":17,"Column3":18,"Column4":19}]'