## 1. What makes NumPy.shape() different from NumPy.size()?
- arr.shape returns (3, 4), indicating the array has 3 rows and 4 columns.
- arr.size returns 12, indicating there are a total of 12 elements in the array.
- numpy.shape: Provides the dimensions of the array (e.g., number of rows and columns).
- 
numpy.size: Provides the total count of elements in the array.

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Shape of the array:", arr.shape)  # Output: (3, 4)
print("Size of the array:", arr.size)    # Output: 12

Shape of the array: (3, 4)
Size of the array: 12


## 2. In NumPy, describe the idea of broadcasting ? 
- Broadcasting is particularly useful in scenarios involving element-wise operations across arrays of different shapes without the need for explicit    looping.
- It is widely used in mathematical computations, data analysis, and machine learning.

In [2]:
# Simple Broadcasting 
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = A + B
print(C) 


[5 7 9]


In [3]:
# Broadcasting with Scalar
import numpy as np

A = np.array([1, 2, 3])
B = 2

C = A + B
print(C) 

[3 4 5]


In [4]:
# Higher Dimension Broadcasting
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

C = A + B
print(C)  


[[11 22 33]
 [14 25 36]]


In [6]:
# Incompatible Shapes 
"""import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2])

# This will raise a ValueError
C = A + B"""

'import numpy as np\n\nA = np.array([[1, 2, 3], [4, 5, 6]])\nB = np.array([1, 2])\n\n# This will raise a ValueError\nC = A + B'

## What makes Python better than other libraries for numerical computation?
Python is a popular choice for numerical computation due to several key advantages it offers over other programming languages and libraries. 
Here are some of the main reasons why Python is often considered better for numerical computation:

1. Rich Ecosystem of Libraries
NumPy: Provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
SciPy: Builds on NumPy and provides additional functionality for scientific and technical computing, including modules for optimization, integration, interpolation, eigenvalue problems, and more.
Pandas: Offers powerful, flexible data structures like DataFrames, which are ideal for data manipulation and analysis.
Matplotlib and Seaborn: Libraries for data visualization, allowing users to create static, interactive, and animated visualizations in Python.
SymPy: Provides symbolic mathematics capabilities, useful for algebraic manipulation, calculus, solving equations, etc.
Scikit-learn: A powerful library for machine learning, offering simple and efficient tools for data mining and data analysis.
2. Ease of Learning and Use
Readable Syntax: Python's syntax is clear and intuitive, making it accessible to beginners and reducing the learning curve.
High-Level Language: Python abstracts many low-level details, allowing users to focus on solving problems rather than managing memory or dealing with complex syntax.
Interactive Development: Tools like Jupyter Notebooks provide an interactive environment where users can write and test code in small, manageable chunks, visualize data, and document their process.
3. Community and Support
Active Community: Python has a large, active community of developers who contribute to a wealth of tutorials, documentation, and forums, making it easier to find help and resources.
Extensive Documentation: Most Python libraries are well-documented, with comprehensive guides and examples that help users understand how to use various functions and tools.
4. Interoperability
Integration with Other Languages: Python can interface with libraries written in C, C++, and Fortran, allowing users to leverage high-performance code while maintaining the simplicity of Python.
Interoperability with Other Tools: Python can easily integrate with web services, databases, and other applications, making it a versatile choice for a wide range of tasks.
5. Performance
Optimized Libraries: Libraries like NumPy and SciPy are highly optimized and written in C, providing near C-level performance for many numerical operations.
Parallel Computing: Python supports parallel and distributed computing through libraries like Dask, joblib, and multiprocessing, allowing for efficient computation on large datasets.
6. Extensibility
Custom Extensions: Users can write custom extensions in C or Cython to optimize performance-critical sections of their code.
Rich Set of Tools: Python's ecosystem includes many tools for profiling, debugging, and optimizing code, such as cProfile, line_profiler, and PyCharm.
7. Versatility
General-Purpose Language: Unlike some languages that are specialized for numerical computation, Python is a general-purpose language. This makes it suitable for a wide range of applications, from web development to data analysis, machine learning, and more.
Broad Application: Python is used in many domains including web development, automation, data analysis, artificial intelligence, and scientific research, making it a versatile tool in a programmer's toolkit.
8. Community and Industry Adoption
Industry Standard: Python has become a standard in many industries, particularly in data science and machine learning, leading to better industry support and more job opportunities.
Extensive Use in Academia: Python is widely used in academia for research and teaching, fostering a continuous influx of new tools, libraries, and talent.
Summary

## 4 How does NumPy deal with files?

In [10]:
# Text file 
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('data.txt', data, delimiter=' ')

In [11]:
# Binary Files 
import numpy as np
data = np.array([1, 2, 3, 4, 5])
np.save('data.npy', data)

In [13]:
"""import numpy as np
# Assuming 'data.csv' is a CSV file
data = np.genfromtxt('data.csv', delimiter=',')
print(data)"""

"import numpy as np\n# Assuming 'data.csv' is a CSV file\ndata = np.genfromtxt('data.csv', delimiter=',')\nprint(data)"

## 5. Mention the importance of NumPy.empty().
- It creates a new array of a specified shape and dtype without initializing the array elements to any particular value. 

In [14]:
import numpy as np
# Create a 1000x1000 array without initializing its elements
arr = np.empty((1000, 1000))